### ISSUE TITLE
Getting more information

### ISSUE THREAD

**Issue by Vadru93** [tdebaets/wertweak#1]
Is it possible to get the information like Exception Code, Fault Module etc that we got in earlier Windows versions?
It really sucks for us developers that we can't get more information when our apps crash...

**Comment by tdebaets** [comment]
Yes, once you get the old-style crash dialog again, you should be able to see that info by making the 'problem details' visible ([screenshot](../blob/master/Images/crashreport-after.png?raw=true)).
