### ISSUE TITLE
Not getting full dialog box

### ISSUE THREAD

**Issue by robbely** [tdebaets/wertweak#2]
After following the instructions, running WerTweakTest64.exe and clicking Crash, the dialog box isn't the old one and only gives the option to close the program.

Task Manager confirms that WerTweak64.exe is being loaded with the dialog box.

**Comment by tdebaets** [comment]
Hi, is this on Windows 10 or 11 and what's the exact Windows build number?

What's the output in [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview) when you use `WerTweakTest64.exe` to trigger another crash?

**Comment by robbely** [comment]
Many thanks for the quick reply.

I'm using Windows 10 22H2 Build 19045.3803

The DebugView output is:
```
[27808] WerTweak: C:\WINDOWS\system32\WerFault.exe -u -p 45180 -s 1388
[27808] WerTweak: DLL filename: C:\Users\User\Local Apps\WerTweak\WerTweak.dll
[27808] WerTweak: DLL filename: C:\Users\User\Local Apps\WerTweak\WerTweak64.dll
[27808] WerTweak: Debugging a 64-bit process (native bitness)
[27808] WerTweak: Breakpoint
[27808] WerTweak: Process entry point hit
[27808] WerTweak: Breakpoint
[27808] WerTweak: Debug string: WerTweak: WerTweak start
[27808] WerTweak: Stub breakpoint hit
[27808] WerTweak: Breakpoint
[27808] WerTweak: Debug string: WerTweak: WerReportSubmit dwFlags==8010008
[27808] WerTweak: Debug string: onecore\windows\feedback\core\werdll\lib\securityattributes.cpp(451)\wer.dll!00007FF9977DDA23: (caller: 00007FF9977E4AD7) LogHr(1) tid(209c) 8007109A This operation is only valid in the context of an app container. 
[27808]     [CSecurityAttributes::GetNewRestrictedFileOrDirectorySecurityAttributes]
[27808] WerTweak: Debug string: onecoreuap\internal\shell\inc\private\StateRepoUtil.h(40)\Windows.FileExplorer.Common.dll!00007FF956A7B501: (caller: 00007FF956A7FFE3) ReturnHr(1) tid(85e4) 8000000B The operation attempted to access data outside the valid range 
[27808] WerTweak: Debug string: WerTweak: NewWerUICreate
[27808] WerTweak: Debug string: WerTweak: SetWindowPos with hWndInsertAfter==HWND_TOPMOST, setting SWP_NOZORDER flag
[27808] WerTweak: Done

```

**Comment by tdebaets** [comment]
It looks like the `WerFault.exe` hook works as expected so no issues there. The only problem is that `NewWerUICreate` doesn't get called with the `consentFlag` parameter equaling to `WerConsentHide` (1), which is why WerTweak expects that this parameter is already set to `WerConsentShow` (0) and that no modification is needed.

Does it help if you create a `REG_DWORD` registry value called `DontShowUI` with value 0 in either `HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting` or `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting`?

**Comment by robbely** [comment]
I tried the reg values as suggested (first one at a time and then both together) but unfortunately still get the same dialog.

**Comment by tdebaets** [comment]
Is this perhaps on a computer that is joined to a domain (e.g. of a company) and that hence is subject to any group policies?

Regardless, it's probably worth checking if you have any non-default registry settings in these keys:

- `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting`
- `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection`

**Comment by robbely** [comment]
The PC is a private PC, not part of a company or domain.

"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting" only has DontShowUI as set earlier

"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection" had AllowTelemetry with a value of 0. I temporarily removed this but to no effect.

There are some changes that I made that might be relevent, but were changed after discovering the issue, so are unlikely to be the cause:

- Group Policy: Windows Error Reporting - Prevent display of the interface for critical errors set to Disabled
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug - Debugger set to a local copy of windbg.exe

**Comment by tdebaets** [comment]
As far as I remember, having `AllowTelemetry` with a value of 0 in the registry would explain the behavior that you're seeing. And I'm not 100% sure anymore, but it's possible that after modifying `AllowTelemetry` (as well as the other registry settings), you need to restart Windows for the changes to take effect.

Additionally, please also check for the existence of `AllowTelemetry` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection`.

**Comment by robbely** [comment]
I removed both cases of AllowTelemetry, the second key also had a setting "MaxTelemetryAllowed" which I also removed for good measure. After a restart, I finally have the old dialog :)

Now I have to decide between telemetry or the crash dialog, unless there is another way to stop the telemetry from leaving my PC.

Either way, many thanks for your help and time solving this :)

EDIT: It turns out a restart isn't necessary, but the AllowTelemetry needs to be removed from both locations.

**Comment by tdebaets** [comment]
No problem! Good to hear that it's solved and thanks for patiently following my suggestions :)

**Comment by robbely** [comment]
As an aside, do you know of anything that would have the same effect as AllowTelemetry=0 that won't affect the crash dialog?

**Comment by tdebaets** [comment]
Nothing that I can immediately think of, sorry. The only thing that comes to mind is to prevent Microsoft's WER servers from being reached by putting their hostnames in the `HOSTS` file.
