### ISSUE TITLE
Crash dialog is still the same after following instructions

### ISSUE THREAD

**Issue by iongsd** [tdebaets/wertweak#3]
What I have tried so far to resolve the issue:
Creating a DontShowUI DWORD value in both HKEY_CURRENT_USER\Software\Microsoft\Windows\Windows Error Reporting and HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting.

Removing "AllowTelemetry" from both HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection.

I am on Windows 10 21H2 LTSC IoT version 10.0.19044.4651.

This is the log provided by DebugView.

**00000001	0.00000000	[3292] WerTweak: C:\Windows\system32\WerFault.exe -u -p 9412 -s 884	
00000002	0.00009340	[3292] WerTweak: DLL filename: C:\wertweak2\WerTweak.dll	
00000003	0.00020990	[3292] WerTweak: DLL filename: C:\wertweak2\WerTweak64.dll	
00000004	0.01759740	[3292] WerTweak: Debugging a 64-bit process (native bitness)	
00000005	0.02365250	[3292] WerTweak: Breakpoint	
00000006	0.07540640	[3292] WerTweak: Process entry point hit	
00000007	0.07552320	[3292] WerTweak: Breakpoint	
00000008	0.07715260	[3292] WerTweak: Debug string: WerTweak: WerTweak start	
00000009	0.07739840	[3292] WerTweak: Stub breakpoint hit	
00000010	0.07747740	[3292] WerTweak: Breakpoint	
00000011	0.18659440	[3292] WerTweak: Debug string: WerTweak: WerReportSubmit dwFlags==8010000	
00000012	0.22985160	[3292] WerTweak: Debug string: onecore\windows\feedback\core\werdll\lib\securityattributes.cpp(451)\wer.dll!00007FFCC8E1CF63: (caller: 00007FFCC8E24017) LogHr(1) tid(f8) 8007109A This operation is only valid in the context of an app container. 	
00000013	0.22985160	[3292]     [CSecurityAttributes::GetNewRestrictedFileOrDirectorySecurityAttributes]	
00000014	0.41197470	[3292] WerTweak: Debug string: WerTweak: NewWerUICreate	
00000015	0.48552510	[3292] WerTweak: Debug string: WerTweak: SetWindowPos with hWndInsertAfter==HWND_TOPMOST, setting SWP_NOZORDER flag	
00000016	5.87367296	[3292] WerTweak: Done**	

I must add that the crash dialog will only appear if I set "Prevent display of the user interface for critical errors" to disabled in gpedit.msc. If it is set to not configured, the application will immediately close and not display the dialog. Also, WerTweak appears to not show the dialog if the program is not responding.

Below is the log for when the application is not responding.
00000001	0.00000000	[9192] WerTweak: werfault.exe /h /shared Global\110655221c9e4f22955c40c4a2ca73ae /t 8828 /p 9932	
00000002	0.00008970	[9192] WerTweak: DLL filename: C:\wertweak2\WerTweak.dll	
00000003	0.00022270	[9192] WerTweak: DLL filename: C:\wertweak2\WerTweak64.dll	
00000004	0.01812560	[9192] WerTweak: Debugging a 64-bit process (native bitness)	
00000005	0.02555750	[9192] WerTweak: Breakpoint	
00000006	0.07699060	[9192] WerTweak: Process entry point hit	
00000007	0.07713950	[9192] WerTweak: Breakpoint	
00000008	0.07870660	[9192] WerTweak: Debug string: WerTweak: WerTweak start	
00000009	0.07913660	[9192] WerTweak: Stub breakpoint hit	
00000010	0.07921610	[9192] WerTweak: Breakpoint	
00000011	0.11901830	[9192] WerTweak: Done

**Comment by tdebaets** [comment]
Just to be sure, the `DontShowUI` DWORD values that you created are both set to 0, right?

The `WerFault.exe` hook itself appears to be working as expected, it's just `NewWerUICreate` that doesn't get called with the expected arguments and that causes WerTweak to think that no customization is needed.

Is your system perhaps joined to a domain (e.g. of a company) and hence subject to any group policies?

Can you check if you have any non-default values (besides `DontShowUI`) in these registry keys?

- `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting`
- `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection`

WerTweak is only meant to customize the behavior on actual application crashes, programs that aren't responding are out of the tool's scope.

**Comment by iongsd** [comment]
My system is not joined to any domain, and both DontShowUI are set to 0. HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DataCollection appears to have a DoNotShowFeedbackNotifications DWORD with a value of 1, which I don't believe is related.

**Comment by iongsd** [comment]
It looks like I have fixed the issue. Windows error reporting was set to disabled in the control panel.

**Comment by tdebaets** [comment]
Thanks for reporting back the solution! I believe that that setting in Control Panel corresponds to the `Disabled` value in `SOFTWARE\Microsoft\Windows\Windows Error Reporting` (either `HKEY_LOCAL_MACHINE` or `HKEY_CURRENT_USER`).
