### ISSUE TITLE
Builing

### ISSUE THREAD

**Issue by marcocajon** [tdebaets/wertweak#4]
Hey and thanks for this great tool, I am not very experienced with C++ so as you would guess I am not having luck with the building process, could you share some steps to get it rolling?

**Comment by tdebaets** [comment]
It should just be a matter of opening the solution in Visual Studio 2019 and starting the build. Which specific issue are you facing?

**Comment by marcocajon** [comment]
`1>------ Build started: Project: WerTweakTest, Configuration: Debug|x64 ------
2>------ Build started: Project: WerTweak, Configuration: Debug|x64 ------
3>------ Build started: Project: WerTweakInject, Configuration: Debug|x64 ------
4>------ Build started: Project: libcommon, Configuration: Debug|x64 ------
1>H:\wertweak\Source\WerTweakTest\WerTweakTest.vcxproj(28,3): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
3>H:\wertweak\Source\WerTweakInject\WerTweakInject.vcxproj(27,3): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
2>H:\wertweak\Source\WerTweak\WerTweak.vcxproj(28,3): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
4>H:\wertweak\common\C\libcommon\VS2019\libcommon.vcxproj(51,3): error MSB4019: The imported project “C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props” was not found. Confirm that the expression in the Import declaration “C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\\Microsoft.Cpp.Default.props” is correct, and that the file exists on disk.
========== Build: 0 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========
Build failed.`

**Comment by marcocajon** [comment]
Nvm I got it

**Comment by tdebaets** [comment]
Would it be possible to explain how you fixed it, so that others that have the same problem can learn from it too? Thanks!
